"""estrutura inicial limpa

Revision ID: 57206aeedfec
Revises: 
Create Date: 2025-07-17 14:32:22.805881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57206aeedfec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_index(op.f('ix_categorias_nome'), 'categorias', ['nome'], unique=True)
    op.create_table('centros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_centros_id'), 'centros', ['id'], unique=False)
    op.create_index(op.f('ix_centros_nome'), 'centros', ['nome'], unique=False)
    op.create_table('atletas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('idade', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('altura', sa.Float(), nullable=True),
    sa.Column('sexo', sa.String(length=1), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('centro_treinamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['centro_treinamento_id'], ['centros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atletas_cpf'), 'atletas', ['cpf'], unique=True)
    op.create_index(op.f('ix_atletas_id'), 'atletas', ['id'], unique=False)
    op.create_index(op.f('ix_atletas_nome'), 'atletas', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atletas_nome'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_id'), table_name='atletas')
    op.drop_index(op.f('ix_atletas_cpf'), table_name='atletas')
    op.drop_table('atletas')
    op.drop_index(op.f('ix_centros_nome'), table_name='centros')
    op.drop_index(op.f('ix_centros_id'), table_name='centros')
    op.drop_table('centros')
    op.drop_index(op.f('ix_categorias_nome'), table_name='categorias')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
